Repository gamer-1478/chepobin-public, pull requests merged in 2021-10, with the labels that each got.

#7 Fixes issue #6
  package-lock.json
  package.json
  server.js
Labels: hacktoberfest-accepted

#10 Implement Express Js Router and move all different routes to routes folder.
  controllers/api.js
  package-lock.json
  package.json
  routes/apiRoute.js
  server.js
  utilities/api.js
Labels: enhancement, hacktoberfest-accepted

#14 Implemented Password hashing for adding and retrieving cheps.
  package-lock.json
  package.json
  utilities/api.js
Labels: hacktoberfest, hacktoberfest-accepted
